-- Donnees reelles des 2 hotels (Mykonos). Genere par scripts/build-seed.mjs.
-- Prix = prix PAR NUIT en centimes d'euro (total sejour = x 2 nuits, calcule cote serveur). Stocks A CONFIRMER.

insert into hotels (id, name, slug, description, location, stars, photos, capacity_max, sort_order) values
('santa-marina', 'Santa-Marina - Mykonos', 'santa-marina-mykonos', 'Santa Marina, a Luxury Collection Resort : presqu''ile privee, plage, villas avec piscine et service d''exception.', 'Ornos Bay, Mykonos', 5, '["/hotels/aerialandbeachsantamarina.jpg"]'::jsonb, 42, 1),
('once-mykonos', 'Once in Mykonos', 'once-in-mykonos', 'Boutique-hotel de luxe perche au-dessus de la mer Egee, design contemporain et vue panoramique sur Mykonos.', 'Mykonos, Grèce', 5, '["/hotels/once.webp"]'::jsonb, 12, 2)
on conflict (id) do nothing;

insert into room_types (id, hotel_id, name, capacity, price_cents, description, photos, stock_total, sort_order) values
('santa-marina-resort-room', 'santa-marina', 'Resort Room', 2, 48200, '2 Personnes — 482 € / nuit (séjour de 2 nuits).', '["/hotels/resort-room-1.jpeg","/hotels/resort-room-2.jpeg"]'::jsonb, 6, 1),
('santa-marina-superior-sea-view-room', 'santa-marina', 'Superior Sea View Room', 2, 57300, '2 Personnes — 573 € / nuit (séjour de 2 nuits).', '["/hotels/superior-sea-view-room-1.jpeg","/hotels/superior-sea-view-room-2.jpeg"]'::jsonb, 6, 2),
('santa-marina-deluxe-sea-view-room', 'santa-marina', 'Deluxe Sea View Room', 3, 68700, '3 Personnes — 687 € / nuit (séjour de 2 nuits).', '["/hotels/deluxe-sea-view-room-1.jpeg","/hotels/deluxe-sea-view-room-2.jpeg","/hotels/deluxe-sea-view-room-3.jpeg"]'::jsonb, 6, 3),
('santa-marina-resort-suites-sea-view', 'santa-marina', 'Resort Suites Sea View', 4, 98300, '3 Personnes ou 2 adultes 2 enfants — 983 € / nuit (séjour de 2 nuits).', '["/hotels/resort-sea-view-suite-1.jpeg","/hotels/resort-sea-view-suite-2.jpeg","/hotels/resort-sea-view-suite-3.jpeg"]'::jsonb, 3, 4),
('santa-marina-luxury-suites-sea-view', 'santa-marina', 'Luxury Suites Sea View', 4, 117700, '3 Personnes ou 2 adultes 2 enfants — 1177 € / nuit (séjour de 2 nuits).', '["/hotels/luxury-sea-view-suite-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/luxury-sea-view-suite-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/luxury-sea-view-suite-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/luxury-sea-view-suite-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg"]'::jsonb, 3, 5),
('santa-marina-luxury-sea-view-suite-with-private-pool', 'santa-marina', 'Luxury Sea View Suite with Private Pool', 4, 175200, '3 Personnes ou 2 adultes 2 enfants — 1752 € / nuit (séjour de 2 nuits).', '["/hotels/luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-7_800x800_auto.jpg","/hotels/luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-6_800x800_auto.jpg"]'::jsonb, 3, 6),
('santa-marina-two-bedroom-luxury-sea-view-suite-with-private-', 'santa-marina', 'Two-Bedroom Luxury Sea View Suite with Private Pool', 4, 252000, '4 Personnes — 2520 € / nuit (séjour de 2 nuits).', '["/hotels/2-bedroom-luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/2-bedroom-luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/2-bedroom-luxury-sea-view-pool-suite-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg"]'::jsonb, 3, 7),
('santa-marina-villa-coral-2-bedroom-villa', 'santa-marina', 'Villa Coral - 2 Bedroom Villa', 4, 195100, '4 Personnes — 1951 € / nuit (séjour de 2 nuits).', '["/hotels/2-bedroom-coral-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/2-bedroom-coral-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/2-bedroom-coral-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/2-bedroom-coral-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg"]'::jsonb, 1, 8),
('santa-marina-villa-crystal-2-bedroom-villa', 'santa-marina', 'Villa Crystal - 2 Bedroom Villa', 4, 228700, '4 Personnes — 2287 € / nuit (séjour de 2 nuits).', '["/hotels/2-bedroom-crystal-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/2-bedroom-crystal-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/2-bedroom-crystal-villa-santa-marina-a-luxury-collection-resort-mykonos-5_800x800_auto.jpg","/hotels/2-bedroom-crystal-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/2-bedroom-crystal-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg"]'::jsonb, 1, 9),
('santa-marina-villa-emerald-2-bedroom-villa', 'santa-marina', 'Villa Emerald - 2 Bedroom Villa', 4, 246300, '4 Personnes — 2463 € / nuit (séjour de 2 nuits).', '["/hotels/3-bedroom-emerald-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/3-bedroom-emerald-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/3-bedroom-emerald-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-5_800x800_auto.jpg","/hotels/3-bedroom-emerald-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg"]'::jsonb, 1, 10),
('santa-marina-villa-pearl-3-bedroom-villa', 'santa-marina', 'Villa Pearl - 3 Bedroom Villa', 6, 246300, '6 Personnes — 2463 € / nuit (séjour de 2 nuits).', '["/hotels/3-bedroom-pearl-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/3-bedroom-pearl-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/3-bedroom-pearl-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg"]'::jsonb, 1, 11),
('santa-marina-villa-lapis-lazuli-3-bedroom-villa', 'santa-marina', 'Villa Lapis Lazuli - 3 Bedroom Villa', 6, 326000, '6 Personnes — 3260 € / nuit (séjour de 2 nuits).', '["/hotels/3-bedroom-lapis-lazuli-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/3-bedroom-lapis-lazuli-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/3-bedroom-lapis-lazuli-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/3-bedroom-lapis-lazuli-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg"]'::jsonb, 1, 12),
('santa-marina-villa-sapphire-3-bedroom-villa', 'santa-marina', 'Villa Sapphire - 3 Bedroom Villa', 6, 294700, '6 Personnes — 2947 € / nuit (séjour de 2 nuits).', '["/hotels/3-bedroom-sapphire-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/3-bedroom-sapphire-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/3-bedroom-sapphire-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg"]'::jsonb, 1, 13),
('santa-marina-villa-amethyst-3-bedroom-villa', 'santa-marina', 'Villa Amethyst - 3 Bedroom Villa', 6, 324300, '6 Personnes — 3243 € / nuit (séjour de 2 nuits).', '["/hotels/4-bedroom-amethyst-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/4-bedroom-amethyst-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/4-bedroom-amethyst-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg"]'::jsonb, 1, 14),
('santa-marina-villa-topaz-4-bedroom-villa', 'santa-marina', 'Villa Topaz - 4 Bedroom Villa', 8, 294700, '8 Personnes — 2947 € / nuit (séjour de 2 nuits).', '["/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-8_800x800_auto.jpg","/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-6_800x800_auto.jpg","/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-7_800x800_auto.jpg","/hotels/4-bedroom-topaz-sea-view-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg"]'::jsonb, 1, 15),
('santa-marina-villa-ruby-4-bedroom-villa', 'santa-marina', 'Villa Ruby - 4 Bedroom Villa', 8, 319800, '8 Personnes — 3198 € / nuit (séjour de 2 nuits).', '["/hotels/4-bedroom-ruby-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/4-bedroom-ruby-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/4-bedroom-ruby-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg"]'::jsonb, 1, 16),
('santa-marina-villa-diamond-4-bedroom-villa', 'santa-marina', 'Villa Diamond - 4 Bedroom Villa', 8, 348800, '8 Personnes — 3488 € / nuit (séjour de 2 nuits).', '["/hotels/4-bedroom-diamond-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/4-bedroom-diamond-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/4-bedroom-diamond-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/4-bedroom-diamond-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg"]'::jsonb, 1, 17),
('santa-marina-villa-tanzanite-5-bedroom-villa', 'santa-marina', 'Villa Tanzanite - 5 Bedroom Villa', 10, 331700, '10 Personnes — 3317 € / nuit (séjour de 2 nuits).', '["/hotels/5-bedroom-tanzanite-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/5-bedroom-tanzanite-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/5-bedroom-tanzanite-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/5-bedroom-tanzanite-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg"]'::jsonb, 1, 18),
('santa-marina-villa-turquoise-5-bedroom-villa', 'santa-marina', 'Villa Turquoise - 5 Bedroom Villa', 10, 383500, '10 Personnes — 3835 € / nuit (séjour de 2 nuits).', '["/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-5_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-10_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-9_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-2_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-3_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-4_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-8_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-1_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-6_800x800_auto.jpg","/hotels/5-bedroom-turquoise-pool-villa-santa-marina-a-luxury-collection-resort-mykonos-7_800x800_auto.jpg"]'::jsonb, 1, 19),
('once-mykonos-panoramic-double-sea-view-room', 'once-mykonos', 'Panoramic Double Sea View Room', 2, 32000, '2 Personnes — 320 € / nuit (séjour de 2 nuits).', '["/hotels/panoramic-double-sea-view-room-1.jpeg","/hotels/panoramic-double-sea-view-room-2.jpeg","/hotels/panoramic-double-sea-view-room-3.jpeg"]'::jsonb, 6, 1),
('once-mykonos-premium-suite-sea-view', 'once-mykonos', 'Premium Suite Sea View', 2, 32000, '2 Personnes — 320 € / nuit (séjour de 2 nuits).', '["/hotels/premium-suite-sea-view-1.jpeg","/hotels/premium-suite-sea-view-2.jpeg","/hotels/premium-suite-sea-view-3.jpeg"]'::jsonb, 6, 2)
on conflict (id) do nothing;
